# Generated by Django 5.2.4 on 2025-08-02 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodioCefalea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_cefalea_horas', models.IntegerField(help_text='Duración del episodio en horas (1-72)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)], verbose_name='Duración Cefalea (horas)')),
                ('severidad', models.CharField(choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Severa', 'Severa')], max_length=20, verbose_name='Severidad del Dolor')),
                ('localizacion', models.CharField(choices=[('Unilateral', 'Unilateral'), ('Bilateral', 'Bilateral')], max_length=20, verbose_name='Localización del Dolor')),
                ('caracter_dolor', models.CharField(choices=[('Pulsátil', 'Pulsátil'), ('Opresivo', 'Opresivo'), ('Punzante', 'Punzante')], max_length=20, verbose_name='Carácter del Dolor')),
                ('empeora_actividad', models.BooleanField(help_text='¿El dolor empeora con actividad física?', verbose_name='Empeora con Actividad')),
                ('nauseas_vomitos', models.BooleanField(verbose_name='Náuseas o Vómitos')),
                ('fotofobia', models.BooleanField(verbose_name='Sensibilidad a la Luz')),
                ('fonofobia', models.BooleanField(verbose_name='Sensibilidad al Sonido')),
                ('presencia_aura', models.BooleanField(verbose_name='Presencia de Aura')),
                ('sintomas_aura', models.CharField(blank=True, help_text='Síntomas de aura separados por comas. Ej: Visuales, Sensitivos', max_length=200, verbose_name='Síntomas del Aura')),
                ('duracion_aura_minutos', models.IntegerField(default=0, help_text='Duración del aura en minutos (0-120)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Duración del Aura (min)')),
                ('en_menstruacion', models.BooleanField(help_text='¿El episodio ocurrió durante la menstruación?', verbose_name='En menstruación')),
                ('anticonceptivos', models.BooleanField(help_text='¿La paciente usa anticonceptivos hormonales?', verbose_name='Uso de Anticonceptivos')),
                ('categoria_diagnostica', models.CharField(blank=True, choices=[('Migraña sin aura', 'Migraña sin aura'), ('Migraña con aura', 'Migraña con aura'), ('Cefalea de tipo tensional', 'Cefalea de tipo tensional')], help_text='Categorización automática basada en criterios médicos', max_length=50, verbose_name='Categoría Diagnóstica')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='episodios_cefalea', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Episodio de Cefalea',
                'verbose_name_plural': 'Episodios de Cefalea',
                'db_table': 'evaluacion_episodio_cefalea',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['paciente'], name='evaluacion__pacient_c53dc1_idx'), models.Index(fields=['categoria_diagnostica'], name='evaluacion__categor_169188_idx'), models.Index(fields=['creado_en'], name='evaluacion__creado__c0bdea_idx'), models.Index(fields=['severidad'], name='evaluacion__severid_b5269c_idx')],
            },
        ),
    ]