# Generated by Django 5.2.4 on 2025-08-03 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluacion_diagnostico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('sin_confirmar', 'Sin Confirmar'), ('tomado', 'Confirmado Tomado'), ('no_tomado', 'Confirmado No Tomado'), ('tomado_tarde', 'Confirmado Tomado Tarde'), ('tomado_muy_tarde', 'Confirmado Tomado Muy Tarde')], default='activo', max_length=30)),
                ('numero_alerta', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('tiempo_espera', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=50)),
                ('caracteristica', models.CharField(blank=True)),
                ('frecuencia_horas', models.IntegerField(default=8)),
                ('duracion_dias', models.IntegerField()),
                ('hora_de_inicio', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('sin_confirmar', 'Sin Confirmar'), ('tomado', 'Confirmado Tomado'), ('no_tomado', 'Confirmado No Tomado'), ('tomado_tarde', 'Confirmado Tomado Tarde'), ('tomado_muy_tarde', 'Confirmado Tomado Muy Tarde')], default='activo', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendaciones', models.JSONField(default=list)),
                ('notificaciones_generadas', models.JSONField(default=list, verbose_name='IDs de Notificaciones')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('cumplimiento', models.FloatField(default=0.0)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('episodio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento', to='evaluacion_diagnostico.episodiocefalea', verbose_name='Episodio de Cefalea')),
                ('medicamentos', models.ManyToManyField(blank=True, related_name='tratamientos', to='tratamiento.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='usuarios.pacienteprofile', verbose_name='Paciente')),
            ],
        ),
    ]
