# Generated by Django 5.2.4 on 2025-08-02 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('sin_confirmar', 'Sin Confirmar'), ('tomado', 'Confirmado Tomado'), ('no_tomado', 'Confirmado No Tomado'), ('tomado_tarde', 'Confirmado Tomado Tarde'), ('tomado_muy_tarde', 'Confirmado Tomado Muy Tarde')], default='activo', max_length=30)),
                ('numero_alerta', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('tiempo_espera', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=50)),
                ('caracteristica', models.TextField(blank=True)),
                ('frecuencia', models.IntegerField(default=8)),
                ('duracion', models.IntegerField()),
                ('hora_de_inicio', models.TimeField()),
            ],
            options={
                'verbose_name': 'Medicación',
                'verbose_name_plural': 'Medicaciones',
                'db_table': 'Medicacion',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('aplicable_a', models.CharField(choices=[('both', 'Hombre y Mujer'), ('female', 'Mujer'), ('male', 'Hombre')], default='both', max_length=6)),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('sin_confirmar', 'Sin Confirmar'), ('tomado', 'Confirmado Tomado'), ('no_tomado', 'Confirmado No Tomado'), ('tomado_tarde', 'Confirmado Tomado Tarde'), ('tomado_muy_tarde', 'Confirmado Tomado Muy Tarde')], default='activo', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('cumplimiento', models.FloatField(default=0.0)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('notificaciones_generadas', models.JSONField(blank=True, default=list)),
                ('medicaciones', models.ManyToManyField(blank=True, related_name='tratamientos', to='tratamiento.medicacion')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medicoprofile')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pacienteprofile')),
                ('recomendaciones', models.ManyToManyField(blank=True, related_name='tratamientos', to='tratamiento.recomendacion')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tratamiento',
            },
        ),
    ]
