# Generated by Django 5.2.4 on 2025-07-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
