# Generated by Django 5.2.4 on 2025-08-03 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='usuarios.pacienteprofile', verbose_name='Paciente'),
            preserve_default=False,
        ),
    ]
