# Generated by Django 5.2.4 on 2025-07-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0002_tratamiento_activo_tratamiento_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='frecuencias',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='frecuencia',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='identificacion',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
