# Generated by Django 5.2.4 on 2025-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0003_remove_medicamento_frecuencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='identificacion',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
