# Generated by Django 5.2.4 on 2025-08-03 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('hora', models.TimeField(verbose_name='Hora de la cita')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('urgente', models.BooleanField(default=False, verbose_name='Es urgente')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la consulta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'tipo_usuario': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_doctor', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas_cita',
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita_proxima', 'Cita Próxima')], default='cita_proxima', max_length=15)),
                ('fecha', models.DateField(verbose_name='Fecha del recordatorio')),
                ('hora', models.TimeField(verbose_name='Hora del recordatorio')),
                ('mensaje', models.TextField(verbose_name='Mensaje del recordatorio')),
                ('enviado', models.BooleanField(default=False, verbose_name='¿Fue enviado?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='agendamiento_citas.cita')),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'db_table': 'citas_recordatorio',
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['doctor', 'fecha'], name='citas_cita_doctor__31fd57_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha'], name='citas_cita_pacient_dceff6_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'hora'], name='citas_cita_fecha_46fbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_cita_estado_2000d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('doctor', 'fecha', 'hora')},
        ),
        migrations.AddIndex(
            model_name='recordatorio',
            index=models.Index(fields=['paciente', 'fecha'], name='citas_recor_pacient_3c3192_idx'),
        ),
        migrations.AddIndex(
            model_name='recordatorio',
            index=models.Index(fields=['fecha', 'hora'], name='citas_recor_fecha_0bdbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='recordatorio',
            index=models.Index(fields=['enviado'], name='citas_recor_enviado_d3a936_idx'),
        ),
    ]
